### ISSUE TITLE
requirements.txt not part of pypi 0.5 release

### ISSUE THREAD

**Issue by sg-** [0xc0170/project_generator#90]
Searching for project-generator>=0.5
Reading https://pypi.python.org/simple/project_generator/
Best match: project-generator 0.5
Downloading https://pypi.python.org/packages/source/p/project_generator/project_generator-0.5.zip#md5=5834faed5887dab70718e8d8f4b20415
Processing project_generator-0.5.zip
Writing c:\users\deskto~1\appdata\local\temp\easy_install-dxynxf\project_generator-0.5\setup.cfg
Running project_generator-0.5\setup.py -q bdist_egg --dist-dir c:\users\deskto~1\appdata\local\temp\easy_install-dxynxf\project_generator-0.5\egg-dist-tmp-stmisq
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    url = "",
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "build\bdist.win-amd64\egg\setuptools\command\install.py", line 67, in run
  File "build\bdist.win-amd64\egg\setuptools\command\install.py", line 117, in do_egg_install
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 370, in run
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 594, in easy_install
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 645, in install_item
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 693, in process_distribution
  File "build\bdist.win-amd64\egg\pkg_resources.py", line 618, in resolve
  File "build\bdist.win-amd64\egg\pkg_resources.py", line 870, in best_match
  File "build\bdist.win-amd64\egg\pkg_resources.py", line 882, in obtain
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 613, in easy_install
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 643, in install_item
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 833, in install_eggs
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 1055, in build_and_install
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 1040, in run_setup
  File "build\bdist.win-amd64\egg\setuptools\sandbox.py", line 68, in run_setup
  File "build\bdist.win-amd64\egg\setuptools\sandbox.py", line 114, in run
  File "build\bdist.win-amd64\egg\setuptools\sandbox.py", line 67, in runner
  File "build\bdist.win-amd64\egg\setuptools\sandbox.py", line 43, in _execfile
  File "c:\users\deskto~1\appdata\local\temp\easy_install-dxynxf\project_generator-0.5\setup.py", line 21, in <module>

  File "C:\Python27\lib\site-packages\pip\req.py", line 1546, in parse_requirements
    session=session,
  File "C:\Python27\lib\site-packages\pip\download.py", line 278, in get_file_content
    raise InstallationError('Could not open requirements file: %s' % str(e))
pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by 0xc0170** [comment]
Thanks,  will fix that
